name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Update to v3
      - name: Setup Node
        uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: '20'  # Update to Node.js 20
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test
